## Write a function so that the columns of the output matrix are powers of the input vector.
## The order of the powers is determined by the increasing boolean argument. Specifically, when
## increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

## HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
n = 5
matrix = np.column_stack([x**(n-i-1) for i in range(n)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [2]:
import numpy as np
y = np.array([1,2,3,4,5])
n = 5
mat=np.vander(y,n,increasing=False)
print(mat)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [3]:
np.linalg.det(matrix)

287.9999999999962

In [4]:
np.linalg.det(mat)

287.9999999999962

In [5]:
import numpy as np
x= np.array ([1,2,3,4,5])
n = 6
matrix1= np.vander(x,n,increasing=False)
print(matrix1)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]


## Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def moving_average(list1,windows):
    

        cumsum=[0]
        mov=[]
        for i,x in enumerate(list1,1):
            cumsum.append(cumsum[i-1]+x)
            if i>=windows:
                mov.append(round((cumsum[i]-cumsum[i-windows])/windows,3))
        return mov

In [7]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
win = 3 
moving_average(mylist,win)

[5.0,
 4.667,
 5.667,
 6.667,
 9.667,
 28.667,
 49.333,
 72.667,
 84.0,
 93.333,
 116.333]